// Generated by Selenium IDE
package junit;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void search() {
    driver.get("https://www.google.com/");
    driver.findElement(By.id("APjFqb")).sendKeys("books");
    driver.findElement(By.xpath("//form/div")).click();
    driver.findElement(By.xpath("(//input[@name=\'btnK\'])[2]")).click();
    driver.findElement(By.xpath("//div[@id=\'rso\']/div/div/g-section-with-header/div/div/div/div/span/span")).click();
    driver.findElement(By.id("dimg_6")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div[3]")).click();
    driver.findElement(By.xpath("//nav/ul/li[2]/a")).click();
  }
}
