// Generated by Selenium IDE
package junit;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ShopTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void shop() throws Exception {
    driver.get("https://www.google.com/");
    Thread.sleep(5000);
    driver.findElement(By.id("APjFqb")).sendKeys("books");
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".ikrT4e")).click();
    Thread.sleep(5000);
    driver.findElement(By.cssSelector("center:nth-child(1) > .gNO89b")).click();
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".hdtb-mitem:nth-child(4) svg")).click();
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".tzVsfd:nth-child(2) .VlHyHc")).click();
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".KZ4CUc > .tzVsfd:nth-child(1) .VlHyHc")).click();
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".tzVsfd:nth-child(2) .VlHyHc")).click();
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".KZ4CUc > .tzVsfd:nth-child(1) .VlHyHc")).click();
  }
}
