// Generated by Selenium IDE
package junit;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UntitledTest1 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() throws Exception {
    driver.get("https://www.google.com/");
    Thread.sleep(5000);
  WebElement s=  driver.findElement(By.id("APjFqb"));
    s.sendKeys("books");
    s.submit();
    Thread.sleep(5000);
    driver.findElement(By.xpath("//div[2]/div/div/span")).click();
    Thread.sleep(5000);
    driver.findElement(By.xpath("//div[7]/div/div/div/div/a/h3")).click();
    Thread.sleep(5000);
    driver.findElement(By.xpath("//li[@id=\'toc-Etymology\']/a/div")).click();
  }
}
